version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    command: "redis-server"
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis-data:/var/lib/redis"
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn dev --legacy-watch
    volumes:
      - ./src:/usr/app/src
      - /usr/app/node_modules
      - ./nodemon.json:/user/app/nodemon.json
    stdin_open: true
    depends_on:
      - postgres
      - redis
    ports:
      - "4000:4000"
